plugins {
    id 'java'
    id 'org.springframework.boot' version '3.4.2'
    id 'io.spring.dependency-management' version '1.1.7'
}

group = 'com.example'
version = '0.0.1-SNAPSHOT'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

repositories {
    mavenCentral()
    gradlePluginPortal()
}

dependencies {
    implementation 'org.springframework.boot:spring-boot-starter-web'
    implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
    implementation 'org.springframework.boot:spring-boot-starter'
    implementation 'org.springdoc:springdoc-openapi-starter-webmvc-ui:2.8.5'
    implementation 'org.springdoc:springdoc-openapi-starter-webmvc-api:2.8.5'
    implementation 'org.postgresql:postgresql'
    implementation 'org.springframework.boot:spring-boot-starter-test:3.4.2'
    implementation 'org.liquibase:liquibase-core'
    testImplementation 'org.junit.jupiter:junit-jupiter-api:5.8.2'
    testImplementation 'org.junit.jupiter:junit-jupiter-engine:5.8.2'
    implementation 'org.junit.platform:junit-platform-launcher:1.12.0-RC2'
    implementation 'com.h2database:h2:2.3.232'
    implementation 'org.hibernate:hibernate-core:7.0.0.Beta4'
    implementation 'org.hibernate.validator:hibernate-validator:9.0.0.CR1'

    implementation 'jakarta.validation:jakarta.validation-api:3.1.1'
    implementation 'org.glassfish:jakarta.el:4.0.2'
}

// Укажите абсолютный путь к docker-compose в ваших задачах Gradle
task composeUpDb(type: Exec) {
    commandLine '/usr/local/bin/docker-compose', '-f', 'docker-compose-db.yml', 'up', '-d'
}

task composeDownDb(type: Exec) {
    commandLine '/usr/local/bin/docker-compose', '-f', 'docker-compose-db.yml', 'down'
}

task composeUpApp(type: Exec) {
    commandLine '/usr/local/bin/docker-compose', '-f', 'docker-compose-app.yml', 'up', '-d'
}

task composeDownApp(type: Exec) {
    commandLine '/usr/local/bin/docker-compose', '-f', 'docker-compose-app.yml', 'down'
}

// Задача для проверки доступности базы данных
task waitForDb {
    doLast {
        def maxRetries = 10
        def retryInterval = 2000 // 2 seconds
        def attempt = 1
        while (attempt <= maxRetries) {
            try {
                def socket = new Socket('localhost', 5432)
                socket.close()
                println 'Database is available'
                break
            } catch (Exception e) {
                println "Waiting for database... attempt $attempt"
                sleep(retryInterval)
                attempt++
            }
        }
        if (attempt > maxRetries) {
            throw new GradleException('Database is not available after multiple attempts')
        }
    }
}

// Задача для запуска базы данных и приложения
task runDbAndApp(dependsOn: ['composeUpDb', 'waitForDb', 'bootRun']) {
    group = 'application'
    description = 'Starts the database container and then runs the Spring Boot application'
}

// Настройка задачи bootRun для использования профиля docker
bootRun {
    args = ['--spring.profiles.active=docker']
}